// Generated by CoffeeScript 1.9.3
var conn, conts, get, mysql, save;

mysql = require('mysql');

conts = require('../constants');

conn = mysql.createConnection({
  host: conts.db.host,
  user: conts.db.username,
  password: conts.db.password,
  database: conts.db.database,
  port: conts.db.port
});

conn.connect();

save = function(files, callback) {
  var co, content, file, i, insertSQL, len, results;
  co = {
    counts: 0,
    data: []
  };
  results = [];
  for (i = 0, len = files.length; i < len; i++) {
    file = files[i];
    co.counts += 1;
    content = files[file];
    insertSQL = "insert into pictures(pictureid, address) values('" + content.name + "', '" + content.url + "')";
    results.push(conn.query(insertSQL, function(err, res) {
      if (err) {
        console.log(err);
      }
      console.log(res);
      return callback(res);
    }));
  }
  return results;
};

get = function(pictureid, callback) {};
