// Generated by CoffeeScript 1.9.3
var conn, conts, deleteSQL, insertSQL, mysql, selectSQL, updateSQL;

mysql = require('mysql');

conts = require('../constants');

conn = mysql.createConnection({
  host: conts.db.host,
  user: conts.db.username,
  password: conts.db.password,
  database: conts.db.database,
  port: conts.db.port
});

conn.connect();

insertSQL = 'insert into t_user (name) values "conan"), "fens.me")';

selectSQL = 'select * from t_user limit 10';

deleteSQL = 'delete from t_user';

updateSQL = 'update t_user set name="conan update"  where name="conan"';

conn.query(deleteSQL, err0, res0(function() {
  if (err0) {
    console.log(err0);
  }
  console.log("DELETE Return ==> ");
  console.log(res0);
  return conn.query(insertSQL, function(err1, res1) {
    if (err1) {
      console.log(err1);
    }
    console.log("INSERT Return ==> ");
    console.log(res1);
    return conn.query(selectSQL, function(err2, rows) {
      var i, j, len;
      if (err2) {
        console.log(err2);
      }
      console.log("SELECT ==> ");
      for (j = 0, len = rows.length; j < len; j++) {
        i = rows[j];
        console.log(rows[i]);
      }
      return conn.query(updateSQL, function(err3, res3) {
        if (err3) {
          console.log(err3);
        }
        console.log("UPDATE Return ==> ");
        console.log(res3);
        return conn.query(selectSQL, function(err4, rows2) {
          var k, len1, results;
          if (err4) {
            console.log(err4);
          }
          console.log("SELECT ==> ");
          results = [];
          for (k = 0, len1 = rows2.length; k < len1; k++) {
            i = rows2[k];
            results.push(console.log(rows2[i]));
          }
          return results;
        });
      });
    });
  });
}));

conn.end();
