// Generated by CoffeeScript 1.9.3
var add, conn, conts, mysql, read;

mysql = require('mysql');

conts = require('../constants');

conn = mysql.createConnection({
  host: conts.db.host,
  user: conts.db.username,
  password: conts.db.password,
  database: conts.db.database,
  port: conts.db.port
});

conn.connect();

add = function(idcard) {
  var updateSQL;
  updateSQL = "update support set number=number+1 where idcard= '" + idcard + "'' ";
  return conn.query(updateSQL, function(err, res) {
    if (err) {
      console.log(err);
    }
    console.log(res);
    return callback(res);
  });
};

read = function(idcard, callback) {
  var selectSQL;
  selectSQL = "select number from support where idcard= '" + idcard + "'' ";
  return conn.query(selectSQL, function(err, res) {
    if (err) {
      console.log(err);
    }
    console.log(res);
    return callback(res);
  });
};

conn.end();

module.exports = {
  add: add,
  read: read
};
